swagger: '2.0'
info:
  title: Skin Cancer Detection API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
paths:
  /melanoma/predict:
    post:
      tags: [skin cancer, predict]
      operationId: image_predict
      summary: Predict whether the mole on the image is a melanoma
      parameters:
        - name: images
          in: body
          schema:
            type: array
            items:
              $ref: '#/definitions/Image'
          required: true
      responses:
        200:
          description: Return classification result
          schema:
            type: array
            items:
              $ref: '#/definitions/ClfResult'

definitions:
  Image:
      type: object
      properties:
        content:
          description: The image content, base64 encoded
          type: string
          readOnly: true
        source:
          description: The image source, AWS S3 or Google Cloud Platform
          type: string
          readOnly: True

  ClfResult:
    type: object
    properties:
      confidence:
        description: Confidence in the predicted result
        type: number
        format: float
        example: 0.1
      result:
        description: The classification result
        type: string
        readOnly: True
